### ISSUE TITLE
You have repeated code, Both inputs does the same functionality! It can be an isolate component!

### ISSUE THREAD

**Issue by itacademyReact** [felipovicc/SPRINT9_REACT_COCKTAIL_APP#1]
https://github.com/felipovicc/SPRINT9_REACT_COCKTAIL_APP/blob/68b7a545c26bd69f8065c427bcf3da23e21f88a0/src/Components/Search/SearchComponent.jsx#L10

**Comment by felipovicc** [comment]
Solved
