### ISSUE TITLE
You can define constants in a file and keep all this paths in it.

### ISSUE THREAD

**Issue by itacademyReact** [felipovicc/SPRINT9_REACT_COCKTAIL_APP#4]
https://github.com/felipovicc/SPRINT9_REACT_COCKTAIL_APP/blob/68b7a545c26bd69f8065c427bcf3da23e21f88a0/src/App.jsx#L56

**Comment by felipovicc** [comment]
Solved in https://github.com/felipovicc/SPRINT9_REACT_COCKTAIL_APP/commit/bd98f227d2682ac19c3640b4459f3272864d7d65
