### ISSUE TITLE
You can wrap all functions that call to localStorage in a same file and use it as a crud API!

### ISSUE THREAD

**Issue by itacademyReact** [felipovicc/SPRINT9_REACT_COCKTAIL_APP#5]
https://github.com/felipovicc/SPRINT9_REACT_COCKTAIL_APP/blob/68b7a545c26bd69f8065c427bcf3da23e21f88a0/src/App.jsx#L23

**Comment by felipovicc** [comment]
Solved in https://github.com/felipovicc/SPRINT9_REACT_COCKTAIL_APP/commit/ac8dd7b1e02785c21958ee02b67c127494a230da
